"""migration

Revision ID: 002
Revises: 001
Create Date: 2026-02-23 14:59:51.600273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_history', sa.Column('timeframe', sa.String(length=10), nullable=False, server_default='1m'))
    op.create_index(op.f('ix_crypto_history_timeframe'), 'crypto_history', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_history_timeframe'), table_name='crypto_history')
    op.drop_column('crypto_history', 'timeframe')
    # ### end Alembic commands ###
