"""migration

Revision ID: 003
Revises: 002
Create Date: 2026-02-23 15:05:39.474587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_daily_id'), 'crypto_daily', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_daily_symbol'), 'crypto_daily', ['symbol'], unique=False)
    op.drop_index('ix_crypto_history_timeframe', table_name='crypto_history')
    op.drop_column('crypto_history', 'timeframe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_history', sa.Column('timeframe', sa.VARCHAR(length=10), server_default=sa.text("'1m'::character varying"), autoincrement=False, nullable=False))
    op.create_index('ix_crypto_history_timeframe', 'crypto_history', ['timeframe'], unique=False)
    op.drop_index(op.f('ix_crypto_daily_symbol'), table_name='crypto_daily')
    op.drop_index(op.f('ix_crypto_daily_id'), table_name='crypto_daily')
    op.drop_table('crypto_daily')
    # ### end Alembic commands ###
