"""migration

Revision ID: 004
Revises: 003
Create Date: 2026-02-23 15:42:34.343225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename price to close for both tables
    op.alter_column('crypto_daily', 'price', new_column_name='close')
    op.alter_column('crypto_history', 'price', new_column_name='close')

    # Add other OHLCV columns
    op.add_column('crypto_daily', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('crypto_daily', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('crypto_daily', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('crypto_daily', sa.Column('volume', sa.Float(), nullable=True))

    op.add_column('crypto_history', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('crypto_history', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('crypto_history', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('crypto_history', sa.Column('volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new columns
    op.drop_column('crypto_history', 'volume')
    op.drop_column('crypto_history', 'low')
    op.drop_column('crypto_history', 'high')
    op.drop_column('crypto_history', 'open')

    op.drop_column('crypto_daily', 'volume')
    op.drop_column('crypto_daily', 'low')
    op.drop_column('crypto_daily', 'high')
    op.drop_column('crypto_daily', 'open')

    # Rename close back to price
    op.alter_column('crypto_history', 'close', new_column_name='price')
    op.alter_column('crypto_daily', 'close', new_column_name='price')
    # ### end Alembic commands ###
